### ISSUE TITLE
Version pré-compilé Ko sur itch.io

### ISSUE THREAD

**Issue by mythonirie** [donjonfi/donjon#136]
Après avoir téléchargé la version pré-compilée donjon-one-v2.zip depuis la page [publier](https://donjon.fi/publier.html), j'ai essayé de déployer mon jeu sur itch.io, 
Cependant le jeu ne charge pas, et la console présente les erreurs suivantes : 
![erreurs console](https://github.com/user-attachments/assets/d64f4a71-d898-4412-b719-7a49f083c64e)

J'ai essayé en remplaçant le contenu de "/assets/jeux/jeu.djn" par mon jeu et aussi en laissant celui d'origine, j'ai le même problème. 

J'ai cette erreur depuis Windows10/firefox 128.0 et Google chrome Version 126.0.6478.183(Build officiel) (64 bits).

**Comment by donjonfi** [comment]
Le problème est lié au fait que itch.io exécute le jeu dans une iFrame et qu’il y a de plus en plus de sécurité par rapport aux iFrames dans les navigateurs. Le nom de domaine où le jeu s’exécute n’est pas le même que celui où itch.io stocke les fichiers ce qui entraine pas mal de problème de sécurité.
Une solution serait peut-être de parvenir à faire en sorte que les fichiers « .js » soient intégrés dans le fichier « .html » sous forme de balises « script » afin d’éviter le téléchargement de sources externes.
En attendant une solution, si tu upload le jeu sur un hébergement perso ou si j’héberge ton jeu sur une url du type https://donjon.fi/jouer/nom-de-ton-jeu tu ne devrais pas rencontrer ce type de souci.

**Comment by donjonfi** [comment]
Est-ce que tu utilises des sons ou des images en plus de ton fichier scénario ?

**Comment by donjonfi** [comment]
Alors j’ai trouvé un début de solution avec un script qui rassemble tous les fichiers js dans le HTML.
Reste que les fichiers CSS également intégrés ne fonctionnent pas mait le jeu est jouable sur itch.io:

![image](https://github.com/user-attachments/assets/aa932396-7598-4deb-9c00-96deabc19294)

**Comment by mythonirie** [comment]
Non, je n'ai pas inclus d'image ou de son. 
(même pas le temps de répondre aux premiers commentaires que tu as déjà une première solution, trop fort)

**Comment by donjonfi** [comment]
J’ai une solution qui semble fonctionner. J’ai trouvé un outil pour intégrer les fichiers « JS » dans le html directement pour éviter les erreurs d’import.
Pour les autres fichiers (images, sons, styles et scénario) ça fonctionne en les gardants à coté.

![image](https://github.com/user-attachments/assets/3f31a24d-95a2-4c35-9f44-f59556aae400)

Je te préviens quand c’est publié sur le site web.

**Comment by donjonfi** [comment]
@kaelhem  à tout hasard tu aurais une piste ?

**Comment by donjonfi** [comment]
Lorsque je référence le fichier css avec ./mon-fichier.css je reçois une 403.
Si je précise qu’il se trouve dans « /html/10944516/mon-fichier.css » ça fonctionne sauf que le dossier numéroté change à chaque fois que j’upload une nouvelle version donc je sais seulement pointer vers un ancien fichier. Enfin j’arrive à rien avec ça…
Dans le même ordre d’idée: avec angular je suis sensé préciser le dossier dans lequel l’application s’exécute sauf que le numéro du dossier change à chaque upload et je ne le connais pas à l’avance…

Ce que je ne parviens pas à comprendre c’est pourquoi tout à fonctionné 1x ce matin sans que j’ai à m’inquiéter du dossier.

**Comment by donjonfi** [comment]
Ok je pense que j’ai trouvé une solution qui fonctionne.
Je dois spécifier `<base href="./"> ` plutôt que `<base href="/">` ou `<base href="/html/012345">` qui ne fonctionnent pas.
On va y arriver !

**Comment by donjonfi** [comment]
@mythonirie j’ai publié une nouvelle version de Donjon-One qui fonctionne avec la dernière version de itch.io:
=> https://donjon.fi/publier.html

**Comment by mythonirie** [comment]
Merci beaucoup @donjonfi
