### ISSUE TITLE
Conjugaison de comprendre

### ISSUE THREAD

**Issue by auraes** [donjonfi/donjon#138]
Je comprends prend un s au présent de l'indicatif.
Dans le fichier commendeur.ts (notemment) :  
> ctxCmd.sortie += "Voici des exemples de commandes que je comprend :\n";

**Comment by auraes** [comment]
Il manque aussi un accent à déçu dans conjugaison.ts :

> ['décevoir', 'deçu']

**Comment by donjonfi** [comment]
Merci pour le signalement. Je vais corriger ça avec la prochaine mise à jour.
